Deploy

diff --git a/.github/workflows/deploy-docs.yml b/.github/workflows/deploy-docs.yml
--- a/.github/workflows/deploy-docs.yml
+++ b/.github/workflows/deploy-docs.yml
@@ -46,10 +46,15 @@ jobs:
 
           if [ -f "docs/mkdocs.yml" ]; then
             echo "MKDOCS_CONFIG=docs/mkdocs.yml" >> "$GITHUB_ENV"
-          else
+          elif [ -f "mkdocs.yml" ]; then
             echo "MKDOCS_CONFIG=mkdocs.yml" >> "$GITHUB_ENV"
+          elif [ -f "../mkdocs.yml" ]; then
+            echo "MKDOCS_CONFIG=../mkdocs.yml" >> "$GITHUB_ENV"
+          else
+            echo "Unable to locate mkdocs.yml" >&2
+            exit 1
           fi
-          
+
       - name: Install dependencies
         run: |
           python -m pip install --upgrade pip
